### ISSUE TITLE
cannot select number of data classes greater than 9

### ISSUE THREAD

**Issue by mapsam** [axismaps/colorbrewer#3]
Looks like there is either a zindex issue with the data class dropdown or a passive suggestion that choosing this color schema with this many classes is a bad idea :stuck_out_tongue: 

![colorbrewer-zindex](https://cloud.githubusercontent.com/assets/1943001/13479202/2711c0f0-e08a-11e5-98e9-be51323201f4.gif)

**Comment by mapsam** [comment]
Upon further inspection, maybe this isn't a bug and, rather, a great way to tell me to not do this.

![colorbrewer-zindex2](https://cloud.githubusercontent.com/assets/1943001/13479293/a76533fe-e08a-11e5-9cb1-a973cbb51fad.gif)

**Comment by awoodruff** [comment]
Well, if it is a great way, it may be by happy accident! I can't recall the reasoning behind programming it to disable those 10–12 options for sequential instead of simply not showing them. Perhaps it's better for the menu to reflect the actual options. Seems like a Sam 1 reaction ("something's broken!") is more likely than Sam 2 ("you're right, 10 classes is a bad idea!").

**Comment by mapsam** [comment]
rude

**Comment by awoodruff** [comment]
If I could close it a thousand times I would.
